server:
  port: 8761

eureka:
  instance:
    appname: central
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
          
swagger: 
  config: 
    refreshrate: 10000
